name: "Build and deploy Github pages"

on:
  push:
    branches: master

jobs:

  build-and-deploy:

    name: "Build and deploy Sphinx documentation"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Install Python dependencies"
        run: |
          pip install setuptools nox
          pip install cffi pillow sphinx sphinx-rtd-theme

      - name: "Build Sphinx Doc"
        run: |
          python setup.py build
          pip install -e .
          python setup.py build_sphinx

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: build/sphinx/html/
