name: "Python Lint and Tests"

on: [push, pull_request]

jobs:

  build-and-test:

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    name: "Build and test Pyguetzli"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Nox"
        run: |
          pip3 install setuptools
          pip3 install nox

      - name: "Lint with flake8"
        run: |
          python3 -m nox --session lint

      - name: "Test with pytest"
        run: |
          python3 -m nox --session test-${{ matrix.python-version }}

