name: "Build and Publish Python Packages"

on:
  push:
    tags: "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  build_sdist:

    name: "Source distribution"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: "Build source distribution"
        run: |
          python setup.py sdist

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/
          retention-days: 1

  build_wheels:

    name: "Build wheels on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
          - macos-10.15

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Build wheels"
        uses: pypa/cibuildwheel@v2.6.0
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          PIP_USE_PEP517: 1
          CIBW_BEFORE_BUILD_MACOS: "find . -name '*.a' -delete"

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl
          retention-days: 1

  publish_pypi:

    name: "Publish packages on PyPI"
    runs-on: ubuntu-latest
    needs:
      - build_sdist
      - build_wheels

    steps:

      - name: "Download artifacts"
        uses: actions/download-artifact@v2

      - name: "Move packages to the dist/ folder"
        run: |
          mkdir dist/
          mv sdist/* dist/
          mv wheels/*.whl dist/

      - name: "Publish packages on PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
